language: csharp
mono: none
dotnet: 3.1
script:
  - dotnet restore
  - dotnet build
# Send coverage data to Coveralls
after_success: 
after_script: 
- dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Exclude="[PersonalPortfolio.Api.Views*]*%2c[*]*Examples?%2c[*]*Startup"
- cat ./tests/TestResults/coverage.info
